name: Stale bot

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-lates
    steps:
    - uses: actions/stale@v3
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has automatically been marked as stale since it hasn't had activity for 30 days. Either comment below to keep it open or close this issue!'
        stale-pr-message: 'This pull request has automatically been marked as stale since it hasn't had activity for 30 days. Either comment below to keep it open or close this pull request!'
        days-before-stale: 14
        days-before-close: 5
        exempt-issue-labels: 'tracking-issue,work-in-progress'
        exempt-pr-labels: 'draft,awaiting-approval'
