name: Validate HTML

on: 
  pull_request:
  push:
    branches: [master]
  
jobs:
  validator:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v1
       with: 
         node-version: '12.x'
     - run: npx html-validate index.html
